# Generated by Django 5.1.1 on 2024-09-20 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_shopadminprofile_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopadminprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shopadminprofile',
            name='validity',
            field=models.CharField(default='payment pending', max_length=20),
        ),
    ]
