# Generated by Django 5.1.1 on 2024-09-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_shopadminprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopadminprofile',
            name='validity',
            field=models.CharField(default='running', max_length=20),
        ),
    ]
