# Generated by Django 5.1.1 on 2024-09-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_shopadminprofile_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopadminprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shopadminprofile',
            name='validity',
            field=models.CharField(default='payment pending', max_length=20),
        ),
    ]
