# Generated by Django 5.1.1 on 2024-09-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_shopadminprofile_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopadminprofile',
            name='is_active',
        ),
        migrations.AddField(
            model_name='shopadminprofile',
            name='validity_status',
            field=models.CharField(default='running', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopadminprofile',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shopadminprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shopadminprofile',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shopadminprofile',
            name='shop_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shopadminprofile',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shopadminprofile',
            name='validity',
            field=models.DateTimeField(),
        ),
    ]
