# Generated by Django 5.1.1 on 2024-09-21 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_shopadminprofile_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopadminprofile',
            name='validity_status',
        ),
        migrations.AddField(
            model_name='shopadminprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shopadminprofile',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shopadminprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shopadminprofile',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shopadminprofile',
            name='shop_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shopadminprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shopadminprofile',
            name='validity',
            field=models.CharField(default='payment pending', max_length=20),
        ),
    ]
