# Generated by Django 5.1.1 on 2024-09-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_shopadminprofile_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopadminprofile',
            name='uid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
