# Generated by Django 5.1.1 on 2024-09-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_shopadminprofile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopadminprofile',
            name='validity',
            field=models.CharField(choices=[('running', 'Running'), ('payment pending', 'Payment Pending')], default='payment pending', max_length=20),
        ),
    ]
