# Generated by Django 5.1.1 on 2024-09-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_shopadminprofile_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopadminprofile',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
