# Generated by Django 5.1.1 on 2024-09-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_shopadminprofile_responsible_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopadminprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/'),
        ),
    ]
