# Generated by Django 5.1.1 on 2024-09-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_shopadminprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopadminprofile',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
