# Generated by Django 5.1.1 on 2024-10-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_shopadminprofile_payment_pending_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopadminprofile',
            name='payment_pending',
        ),
        migrations.AlterField(
            model_name='shopadminprofile',
            name='validity',
            field=models.CharField(choices=[('running', 'Running'), ('payment pending', 'Payment Pending')], default='running', max_length=20),
        ),
    ]
