# Generated by Django 5.1.1 on 2024-10-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_remove_shopadminprofile_payment_pending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopadminprofile',
            name='validity',
            field=models.CharField(choices=[('active', 'Active'), ('payment pending', 'Payment Pending')], default='active', max_length=20),
        ),
    ]
