# Generated by Django 5.1.1 on 2024-10-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_shopadminprofile_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopadminprofile',
            name='validity',
            field=models.CharField(choices=[('running', 'Running'), ('payment pending', 'Payment Pending')], default='running', max_length=20),
        ),
    ]
