# Generated by Django 5.0.6 on 2024-10-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_shopadminprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopadminprofile',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
