# Generated by Django 5.0.6 on 2024-10-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_shopadminprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopadminprofile',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopadminprofile',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopadminprofile',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
