# Generated by Django 5.0.6 on 2024-10-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_shopadminprofile_google_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopadminprofile',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
