# Generated by Django 5.1.1 on 2024-11-20 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_shopadminprofile_expiry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='display_order',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='uploaded_images/'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='shop_admin_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.shopadminprofile'),
        ),
    ]
