# Generated by Django 5.1.1 on 2024-12-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_alter_uploadedimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopadminprofile',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
